# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9418e856d726c5c9e97962a80d577712"
application_url = "https://newer-latino-firms-unwrap.trycloudflare.com"
embedded = true
name = "scaffold-app-tutorial"
handle = "scaffold-app-tutorial-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://newer-latino-firms-unwrap.trycloudflare.com/auth/callback",
  "https://newer-latino-firms-unwrap.trycloudflare.com/auth/shopify/callback",
  "https://newer-latino-firms-unwrap.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "scaffold-app-tutorial.myshopify.com"
automatically_update_urls_on_dev = true
