name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "pnpm prisma generate"
dev = "pnpm prisma migrate deploy && pnpm remix vite:dev --host"
